hyperskill_project:
  id: 79
  ide_files: https://stepik.org/media/attachments/lesson/255229/additional_files.json
  is_template_based: false
stages:
- id: 436
  step: 7210
- id: 437
  step: 7211
- id: 438
  step: 7212
- id: 439
  step: 7213
- id: 440
  step: 7214
- id: 441
  step: 7215
topics:
  0:
  - title: Introduction to Python
    theory_id: 5204
  - title: Overview of the basic program
    theory_id: 5208
  - title: Multi-line programs
    theory_id: 5233
  - title: PEP 8
    theory_id: 5879
  - title: Comments
    theory_id: 6081
  - title: Basic data types
    theory_id: 5852
  - title: Variables
    theory_id: 5859
  - title: Integer arithmetic
    theory_id: 5865
  - title: Boolean logic
    theory_id: 6025
  - title: Membership testing
    theory_id: 8828
  - title: Naming variables
    theory_id: 5885
  - title: List
    theory_id: 5979
  - title: Taking input
    theory_id: 5913
  - title: Program with numbers
    theory_id: 5872
  - title: Comparisons
    theory_id: 5920
  - title: If statement
    theory_id: 5953
  - title: For loop
    theory_id: 6065
  1:
  - title: Files
    theory_id: 6989
  - title: Command line overview
    theory_id: 8977
  - title: IDE
    theory_id: 3805
  - title: Quotes and multi-line strings
    theory_id: 5814
  - title: Type casting
    theory_id: 6224
  - title: Escape sequences
    theory_id: 7130
  - title: Indexes
    theory_id: 6189
  - title: Invoking a function
    theory_id: 5891
  - title: Declaring a function
    theory_id: 5900
  - title: Arguments
    theory_id: 7248
  - title: Operations with list
    theory_id: 6031
  - title: String formatting
    theory_id: 6037
  - title: Basic string methods
    theory_id: 6842
  - title: Split and join
    theory_id: 6972
  - title: Load module
    theory_id: 6019
  - title: Command line arguments
    theory_id: 7981
  - title: Files in Python
    theory_id: 8691
  - title: Reading files
    theory_id: 8139
  - title: Writing files
    theory_id: 8334
  - title: Context manager
    theory_id: 8702
  - title: PyCharm basics
    theory_id: 6193
  2:
  - title: Computer algorithms
    theory_id: 4953
  - title: The big O notation
    theory_id: 4991
  - title: Data structures
    theory_id: 5161
  - title: Stack
    theory_id: 5252
  - title: Stack in Python
    theory_id: 8915
  3:
  - title: World Wide Web
    theory_id: 6633
  - title: HTTP protocol
    theory_id: 6569
  - title: HTTP URL
    theory_id: 6740
  - title: HTTP messages
    theory_id: 6752
  - title: Dictionary
    theory_id: 6481
  - title: Create module
    theory_id: 6057
  - title: Packages
    theory_id: 6384
  - title: Pip
    theory_id: 6230
  - title: 'Requests: retrieving data'
    theory_id: 8603
  - title: HTML basics
    theory_id: 6434
  - title: Tags and attributes
    theory_id: 7536
  - title: HTML page structure
    theory_id: 6491
